### ISSUE TITLE
您好，我想问下关于watcher的问题

### ISSUE THREAD

**Issue by lyzn-wzr** [DMQ/mvvm#29]
在Watcher函数中有一个判断
`  if (typeof expOrFn === 'function') {
    this.getter = expOrFn
  } else {
    this.getter = this.parseGetter(expOrFn)
  }`
我看示例里并没有为function的类型啊，什么情况下这里会触发function的逻辑呢？非常感谢

**Comment by DMQ** [comment]
computed属性用到function
