### ISSUE TITLE
关于watcher.js中的一行代码问题

### ISSUE THREAD

**Issue by radicalviva** [DMQ/mvvm#3]
`Dep.target = watcherInstance`标记订阅者是当前`watcher`实例，强行触发属性定义的`getter`方法
为什么通过获取`watcher`实例，会触发`data`里面的属性的`getter`方法呢？
希望有人帮我解答下呀。

**Comment by DMQ** [comment]
@radicalviva 简单解释一下，你主要是要理解defineProperty这个方法的含义，以及defineProperty中定义的get方法的执行时机，详见截图
![image](https://cloud.githubusercontent.com/assets/6860287/24838222/68f35a5e-1d76-11e7-8b22-feb095a668d9.png)

**Comment by radicalviva** [comment]
@DMQ 
我在`Watch.get`方法测试了下，仅保留`Dep.target = this`而注释掉
`var value = this.vm[exp];Dep.target=null;`也将触发那个属性的`getter`方法
这是我不能理解的。

**Comment by DMQ** [comment]
@radicalviva 在compile.js里面也是有初始化视图需要取值的时候，会触发getter，并不只是在watcher初始化 的时候会触发哈，只需要知道通过defineProperty定义的属性，在取值的时候就会触发getter就行了，有时候不要太砖牛角尖
