### ISSUE TITLE
v-model指令你是如何实现呢，目前看data与UI层单向数据绑定没问题

### ISSUE THREAD

**Issue by codevvvv9** [DMQ/mvvm#34]
想请教你是如何实现UI层 与 data的绑定的

**Comment by DMQ** [comment]
@codevvvv9 看源码这里哈，https://github.com/DMQ/mvvm/blob/master/js/compile.js#L103 
v-model本质上是在v-text等指令基础上，在框架层面添加一个事件监听，去改变data，而不需要调用方自己监听事件
