### ISSUE TITLE
关于constructor

### ISSUE THREAD

**Issue by chroota** [DMQ/mvvm#40]
发现了个不知算不算问题的小问题，就是如果直接将一个对象赋值给构造函数**Function**的**prototype**，导致**Function.prototype.constructor**指向Object了。
如：

```
function Dep() {
       .....
}

Dep.prototype = {
    ......
}

let dep = new Dep();
console.log(dep.constructor)   //Object
```

**Comment by DMQ** [comment]
> 发现了个不知算不算问题的小问题，就是如果直接将一个对象赋值给构造函数**Function**的**prototype**，导致**Function.prototype.constructor**指向Object了。
> 如：
> 
> ```
> function Dep() {
>        .....
> }
> 
> Dep.prototype = {
>     ......
> }
> 
> let dep = new Dep();
> console.log(dep.constructor)   //Object
> ```

这的确是个小问题，可以提个pr过来哈
