### ISSUE TITLE
issue: 对于嵌套的data属性，观察者的回调会同时绑定在父级，以及子级属性上

### ISSUE THREAD

**Issue by LiShuxue** [DMQ/mvvm#43]
复现步骤
1. 修改watcher中的run方法，不加任何验证判断，单纯只执行回调函数
```js
run: function() {
    this.cb.call(this.vm);
}
```
2. 打开mvvm.html文件，并打开控制台页面，执行以下代码
```js
// 生成一个data对象
var data = { a: 'test', b: {c:'test2'} }
// 用data去实例化MVVM
var vm = new MVVM({ data })
// 生成一个观察者，去观察data.b.c的变化，并传入回调函数
new Watcher(vm, '_data.b.c', ()=>console.log('观察到数据c变化，开始执行操作'))
```
3. 再输入以下代码，来验证观察者生效
```js
vm._data.b.c = 'test3'    // 观察到数据c变化，开始执行操作
vm._data.b = {} // 观察到数据c变化，开始执行操作
```
给c赋值，监听到变化，这是正常的。   
但是给b赋值，他也执行c的回调就不对了。原因是，在parseGetter中，我们想获得b.c，就会先执行b的get， 再执行c的get，但是他的watcher都是同一个。  

有什么好的solution吗？我看vue的实现，也没看到怎么处理这个循环绑定watcher的

**Comment by LiShuxue** [comment]
期待您的回复，我对这点疑惑了很长时间，没有什么发现

**Comment by DMQ** [comment]
@LiShuxue 抱歉现在才看到。这里说明一下，监听子属性的时候为什么也需要往父属性的dep添加依赖？主要是为了解决：当父属性是被整个对象重新赋值的场景，保证子属性的绑定值依旧能正常使用，如：
```js
// template
<span>{{ child.name }}</span>

// data
data: {
  child: {
    name: 'childone',
  }
}

// 为了保证以下操作，模板能正常显示出child.name
vm.child = { name: 'childtwo' }
```

当然这里带来的一点副作用你也说到了。如果新赋值的对象没包含对应的`name`属性: `vm.child = {};`，watch的回调也会有多余的执行。但是从另一个角度看，其实是 `name` 的值由`childone`变成了`undefined`，还有从模板更新的角度看，此时模板也需要依赖这个变更的回调来更新模板内容，如果赋值空对象的时候watch没有回调，那么此时模板也不会更新。

**Comment by LiShuxue** [comment]
谢谢，明白了
