### ISSUE TITLE
watcher和vue的watcher对应关系不一样吧

### ISSUE THREAD

**Issue by LesterWeng** [DMQ/mvvm#44]
项目里的一个watcher对应一个指令，而vue源码里是一个watcher对应一个vm，依赖变化触发mountComponent，patch vdom，之所以不一样是因为vue完全使用vdom的原因吗

**Comment by DMQ** [comment]
这里的实现是针对较早版本的vue，vue2支持vdom之后，指令这一块的处理不一样了。vue2中一个组件作用域内的任意数据变化，都会触发update函数执行，也就是 patch vdom相关的操作
