### ISSUE TITLE
关于多个watcher的探讨

### ISSUE THREAD

**Issue by JasonXiang2014** [DMQ/mvvm#53]
看代码的时候发现 每一个动态node节点(携带指令、或者{{text}} 文本节点) 都会生成一个Watcher，这个Watcher 绑定了对应的节点和更新函数，当更新data中的数据时，调用dep.notify(), 触发Watcher里面的update方法，再触发绑定的更新函数，从而实现节点的更新。
但是今天看Vue2.0源码的时候发现，每个Vue实例只会绑定一个Watcher，当调用dep.notify()， Watcher做的事情是创建一个新的虚拟节点，再通过虚拟节点的diff来更新试图，和简易版的MVVM是有差别，不知道理解的对不对。

**Comment by DMQ** [comment]
> 看代码的时候发现 每一个动态node节点(携带指令、或者{{text}} 文本节点) 都会生成一个Watcher，这个Watcher 绑定了对应的节点和更新函数，当更新data中的数据时，调用dep.notify(), 触发Watcher里面的update方法，再触发绑定的更新函数，从而实现节点的更新。 但是今天看Vue2.0源码的时候发现，每个Vue实例只会绑定一个Watcher，当调用dep.notify()， Watcher做的事情是创建一个新的虚拟节点，再通过虚拟节点的diff来更新试图，和简易版的MVVM是有差别，不知道理解的对不对。

@JasonXiang2014 你理解的没问题，Vue2.0和我这里简易版的MVVM(1.0)是有差别，2.0加入了virtual dom之后，后统一在一个update函数中进行virtual dom的diff处理
