### ISSUE TITLE
watch原型中的exp写错了

### ISSUE THREAD

**Issue by zhang-wei-jian** [DMQ/mvvm#54]
![image](https://user-images.githubusercontent.com/75430336/220606380-d1673ef0-2204-445e-ba77-1b6eda409491.png)
如图应该没有找到exp，如果想在原型中拿到exp可以修改为this.exp,因为原型中的this指向watch实例，watch实例中保存过了exp
![~$O2B`T0MF (ZS{J~OI8WU1](https://user-images.githubusercontent.com/75430336/220607286-bba8b001-fbcd-44b1-bc99-1764c9d92c6b.png)

**Comment by DMQ** [comment]
@zhang-wei-jian 收到，readme描述有误，源码已经更新过，我更新下readme
