### ISSUE TITLE
从Dep 到Watcher 这部分有点少

### ISSUE THREAD

**Issue by edward32tnt** [DMQ/mvvm#7]
希望能多讲一点帮助理解

**Comment by yangfan0095** [comment]
有啥问题吗 有的话可以问我 我最近研究了一下

**Comment by DMQ** [comment]
@edward32tnt 文章毕竟有限，看下代码比较好理解，推荐一个方法，可以在关键步骤debugger，逐步来看代码走向，就会更清晰些。
有哪部分疑惑的，可以具体的列一下，大家一起交流

**Comment by jypblue** [comment]
写的挺好的！
