### ISSUE TITLE
Dep.target干嘛的？

### ISSUE THREAD

**Issue by fangxianzheng** [DMQ/mvvm#8]
get里有 if (Dep.target) { dep.depend()} 这段，而后面又直接设置 Dep.target = null 这是为了以后用的吗？看不懂

**Comment by DMQ** [comment]
@fangxianzheng 在observer.js这里，需要给属性添加监听者的时候用到，因为在触发getter的时候，watcher实例不好传递，所以用一个全局属性来标记，添加完后，再移除
![image](https://user-images.githubusercontent.com/6860287/28912189-d8760fb2-7865-11e7-992a-77afa566fa18.png)
