### ISSUE TITLE
关于watcher的问题

### ISSUE THREAD

**Issue by iiijarvis** [DMQ/mvvm#9]
您好 ， 您关于vue双向数据绑定的文章写得灰常好！！！
有小地方还不太理解，能具体讲讲compile初始化的时候watcher有什么用处以及修改input里value值时watcher的调用情况吗？
非常感谢！！！

**Comment by DMQ** [comment]
@lao42981894zh 谢谢，希望对你有帮助！

**Comment by iiijarvis** [comment]
有关watcher.js 那里还不是很懂 ，能具体讲讲吗
watcher.js 中的get方法有什么作用呢？

**Comment by DMQ** [comment]
@lao42981894zh 
watcher.js主要的作用是作为一个观察者的角色，观察某个数据(属性)有变动，然后执行它的回调方法去更新视图。
而要观察数据(属性)变动，就需要在它所观察的这个数据(属性)的getter方法里面去添加订阅者（在observer.js中），要触发数据(属性的)getter方法，只需要执行取值语句就行了。
如: var name = vm.name，就会触发name的getter，watcher.js中的get方法主要是这个作用

**Comment by iiijarvis** [comment]
已在[这里](https://github.com/DMQ/mvvm/issues/3)找到更详细解释
谢谢
